api_platform:
    title: Fantasy Academy API
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/Api/Response'
            - '%kernel.project_dir%/src/Message'
    enable_entrypoint: false
    use_symfony_listeners: true
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        normalization_context:
            skip_null_values: false
