name: Backend tests

on:
    push:
        paths:
            - 'api/**'
            - '.github/workflows/backend-*'
    pull_request:
        paths:
            - 'api/**'
            - '.github/workflows/backend-*'

env:
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fantasy_academy_test?serverVersion=17.0&charset=utf8

jobs:
  tests:
    runs-on: ubuntu-latest
    container: ghcr.io/thedevs-cz/php:8.4

    services:
      postgres:
          image: postgres:17.0
          env:
              POSTGRES_PASSWORD: postgres
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
          ports:
              - 5432:5432

    steps:
      -   uses: actions/checkout@v4
      -   uses: actions/cache@v4
          with:
              path: ./api/vendor
              key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
              restore-keys: |
                  ${{ runner.os }}-composer-

      -   run: composer install --no-scripts --no-progress
          working-directory: ./api

      -   run: vendor/bin/phpunit
          working-directory: ./api


  phpstan:
      runs-on: ubuntu-latest
      container: ghcr.io/thedevs-cz/php:8.4
      steps:
        -   uses: actions/checkout@v4
        -   uses: actions/cache@v4
            with:
                path: ./api/vendor
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                    ${{ runner.os }}-composer-

        -   run: composer install --no-scripts --no-progress
            working-directory: ./api

        -   run: bin/console cache:warmup --env=dev
            working-directory: ./api

        -   run: composer run-script phpstan
            working-directory: ./api


  migrations-up-to-date:
      runs-on: ubuntu-latest
      container: ghcr.io/thedevs-cz/php:8.4
      services:
          postgres:
              image: postgres:17.0
              env:
                  POSTGRES_PASSWORD: postgres
                  POSTGRES_DB: fantasy_academy_test
              options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
              ports:
                  - 5432:5432

      steps:
          -   uses: actions/checkout@v4
          -   uses: actions/cache@v4
              with:
                  path: ./api/vendor
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

          -   run: composer install --no-scripts --no-progress
              working-directory: ./api

          -   run: bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
              working-directory: ./api

          -   run: bin/console doctrine:schema:update --dump-sql
              working-directory: ./api

          -   run: bin/console doctrine:schema:validate
              working-directory: ./api
